name: Password Validator Github Workflows
run-name: Running ??
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependances
        run: npm ci

      - name: Launch Tests
        run: npm test

      - name: Success tests ?
        run: echo "Win"